### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Dede-Git** [nss-evening-cohort-21/rare_v2_server#46]
As a potential user I would like to be able to create an account in the system so that I may use it's features.

Given a potential user wants to create an account in the system
When they select the Register option from the menu
Then they should be directed to a form where they are prompted to enter their User Profile information

Given a potential user has entered their User Profile information
when they click the Register button
Then a new User Profile should be created in the database
And the User Profile should have a user type of Author (this can be ignored for the first sprint)
And the User Profile's creation datetime should be set to the current date end time
And the user should be directed to the homepage

The User Profile information is:

First name
Last name
Bio
Profile Image URL
Email

Client-side:
- Form (separate component)
![Screen Shot 2023-06-19 at 8 19 41 PM](https://github.com/nss-evening-cohort-21/rare_v2_server/assets/106976431/964c5ac0-71a6-485b-a6a5-d25dff75e913)
- created_on automatically created via a dateTime on submit 
- default of false for "active" and "is_staff"
- pass uid from Google auth

- Model after LevelUp Client side 
- Promise for "register user" lives inside auth.js

**Comment by allison-blumenthal** [comment]
- [ ] Backend
- [ ] Frontend
